### DISCUSSION TITLE
[@types/tampermonkey] Cannot augment module 'GM' with value exports because it resolves to a non-module entity.

### DISCUSSION THREAD

**Discussion by NatoBoram** [DefinitelyTyped/DefinitelyTyped#56858] [Issues with a @types package] [answered]
`tsc --noEmit` fails with the following error.

> `node_modules/.pnpm/@types+tampermonkey@4.0.5/node_modules/@types/tampermonkey/index.d.ts:542:15` - error **TS2649**: Cannot augment module `GM` with value exports because it resolves to a non-module entity.

```typescript
/**
 * `GM` has all the `GM_*` apis in promisified form
 */
declare const GM: Readonly<{
```

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/tampermonkey/index.d.ts#L542

```yaml
node: v17.0.1
pnpm: 6.19.1
tsc: Version 4.4.4
"@types/greasemonkey": "^4.0.2"
"@types/tampermonkey": "^4.0.5"
```

https://www.npmjs.com/package/@types/tampermonkey

[a comment by an automated account is not shown]
