### ISSUE TITLE
[@types/serverless] maximumRetryAttempts option missing in functions configuration

### ISSUE THREAD

**Issue by kristiannotari** [DefinitelyTyped/DefinitelyTyped#48137]
~Is something wrong with CI or publishing infrastructure?~

- ~Check the [Infrastructure status updates](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/44317) thread for known issues.~
- ~Leave a message on the [DefinitelyTyped Gitter](http://gitter.im/DefinitelyTyped/DefinitelyTyped).~

~If you know how to fix the issue, make a pull request instead.~

- [x] I tried using the `@types/xxxx` package and had problems.
- [ ] I tried using the latest stable version of tsc. https://www.npmjs.com/package/typescript
- [ ] I have a question that is inappropriate for [StackOverflow](https://stackoverflow.com/).  (Please ask any appropriate questions there).
- [x] [Mention](https://github.com/blog/821-mention-somebody-they-re-notified) the authors (see `Definitions by:` in `index.d.ts`) so they can respond.
  - Authors: @JonathanWilbur, @fredericbarthelet, @bryan-hunter, @ThomasAribart 

---

The option `maximumRetryAttempts` for functions inside the serverless configuration is missing despite the fact I'm using it with serverless.yml with no problems at all (used serverless v1.78.0 and forward).

Example:
```yaml
functions:
  my-function:
    handler: src/path/to/handler
    maximumRetryAttempts: 0
    reservedConcurrency: 1
    events:
      - s3:
          bucket: myBucket
          event: s3:ObjectCreated:*
          rules:
            - prefix: prefix/path
            - suffix: suffix/path
          existing: true
```
